--
-- Create the table children
--
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "梦的解析1", "弗洛伊德", "心理学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "梦的解析2", "弗洛伊德", "心理学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "梦的解析3", "弗洛伊德", "心理学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "梦的解析4", "弗洛伊德", "心理学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "梦的解析5", "弗洛伊德", "心理学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "梦的解析6", "弗洛伊德", "心理学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "梦的解析7", "弗洛伊德", "心理学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "梦的解析8", "弗洛伊德", "心理学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "梦的解析9", "弗洛伊德", "心理学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "梦的解析A", "弗洛伊德", "心理学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "水浒传1", "吴冠中", "古代小说, 替天行道", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "水浒传2", "吴冠中", "古代小说, 替天行道", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "水浒传3", "吴冠中", "古代小说, 替天行道", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "水浒传4", "吴冠中", "古代小说, 替天行道", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "水浒传5", "吴冠中", "古代小说, 替天行道", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "水浒传6", "吴冠中", "古代小说, 替天行道", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "水浒传7", "吴冠中", "古代小说, 替天行道", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "水浒传8", "吴冠中", "古代小说, 替天行道", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "水浒传9", "吴冠中", "古代小说, 替天行道", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "水浒传A", "吴冠中", "古代小说, 替天行道", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "水浒传B", "吴冠中", "古代小说, 替天行道", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "一只红狐狸1", "拉里", "童话,寓言故事,爱心", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "一只红狐狸2", "拉里", "童话,寓言故事,爱心", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "一只红狐狸3", "拉里", "童话,寓言故事,爱心", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "一只红狐狸4", "拉里", "童话,寓言故事,爱心", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "一只红狐狸5", "拉里", "童话,寓言故事,爱心", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "一只红狐狸6", "拉里", "童话,寓言故事,爱心", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "一只红狐狸7", "拉里", "童话,寓言故事,爱心", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "一只红狐狸8", "拉里", "童话,寓言故事,爱心", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "一只红狐狸9", "拉里", "童话,寓言故事,爱心", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 12, "一只红狐狸A", "拉里", "童话,寓言故事,爱心", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "赵式孤儿1", "赵", "心理学,古代", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "赵式孤儿2", "赵", "心理学,古代", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "赵式孤儿3", "赵", "心理学,古代", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "赵式孤儿4", "赵", "心理学,古代", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "赵式孤儿5", "赵", "心理学,古代", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "赵式孤儿6", "赵", "心理学,古代", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "赵式孤儿7", "赵", "心理学,古代", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "赵式孤儿8", "赵", "心理学,古代", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "赵式孤儿9", "赵", "心理学,古代", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "赵式孤儿A", "赵", "心理学,古代", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "钱不是万能的1", "钱", "心理学,成功学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "钱不是万能的2", "钱", "心理学,成功学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "钱不是万能的3", "钱", "心理学,成功学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "钱不是万能的4", "钱", "心理学,成功学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "钱不是万能的5", "钱", "心理学,成功学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "钱不是万能的6", "钱", "心理学,成功学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "钱不是万能的7", "钱", "心理学,成功学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "钱不是万能的8", "钱", "心理学,成功学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "钱不是万能的9", "钱", "心理学,成功学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "钱不是万能的A", "钱", "心理学,成功学", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "孙子兵法1", "孙", "心理学,军事经典,战术", 0, 0, 1, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "孙子兵法2", "孙", "心理学,军事经典,战术", 0, 0, 1, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "孙子兵法3", "孙", "心理学,军事经典,战术", 0, 0, 1, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "孙子兵法4", "孙", "心理学,军事经典,战术", 0, 0, 1, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "孙子兵法5", "孙", "心理学,军事经典,战术", 0, 0, 1, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "孙子兵法6", "孙", "心理学,军事经典,战术", 0, 0, 1, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "孙子兵法7", "孙", "心理学,军事经典,战术", 0, 0, 1, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "孙子兵法8", "孙", "心理学,军事经典,战术", 0, 0, 1, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "孙子兵法9", "孙", "心理学,军事经典,战术", 0, 0, 1, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "孙子兵法A", "孙", "心理学,军事经典,战术", 0, 0, 1, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 21, "孙子兵法B", "孙", "心理学,军事经典,战术", 0, 0, 1, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 22, "李白诗精选1", "李白", "文学,诗歌", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 22, "李白诗精选2", "李白", "文学,诗歌", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 22, "李白诗精选3", "李白", "文学,诗歌", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 22, "李白诗精选4", "李白", "文学,诗歌", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 22, "李白诗精选5", "李白", "文学,诗歌", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 22, "李白诗精选6", "李白", "文学,诗歌", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 22, "李白诗精选7", "李白", "文学,诗歌", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 22, "李白诗精选8", "李白", "文学,诗歌", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 22, "李白诗精选9", "李白", "文学,诗歌", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 22, "李白诗精选A", "李白", "文学,诗歌", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "吴传1", "吴", "军事著作", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "吴传2", "吴", "军事著作", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "吴传3", "吴", "军事著作", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "吴传4", "吴", "军事著作", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "吴传5", "吴", "军事著作", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "吴传6", "吴", "军事著作", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "吴传7", "吴", "军事著作", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "吴传8", "吴", "军事著作", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "吴传9", "吴", "军事著作", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "吴传A", "吴", "军事著作", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "吴传B", "吴", "军事著作", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "郑成功传1", "吕国庆", "名人自传", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "郑成功传2", "吕国庆", "名人自传", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "郑成功传3", "吕国庆", "名人自传", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "郑成功传4", "吕国庆", "名人自传", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "郑成功传5", "吕国庆", "名人自传", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "郑成功传6", "吕国庆", "名人自传", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "郑成功传7", "吕国庆", "名人自传", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "郑成功传8", "吕国庆", "名人自传", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "郑成功传9", "吕国庆", "名人自传", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "郑成功传A", "吕国庆", "名人自传", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "郑成功传B", "吕国庆", "名人自传", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "王的庆宴1", "王子", "小说, 歌功颂德", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "王的庆宴2", "王子", "小说, 歌功颂德", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "王的庆宴3", "王子", "小说, 歌功颂德", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "王的庆宴4", "王子", "小说, 歌功颂德", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "王的庆宴5", "王子", "小说, 歌功颂德", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "王的庆宴6", "王子", "小说, 歌功颂德", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "王的庆宴7", "王子", "小说, 歌功颂德", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "王的庆宴8", "王子", "小说, 歌功颂德", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "王的庆宴9", "王子", "小说, 歌功颂德", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "王的庆宴A", "王子", "小说, 歌功颂德", 0, 0, 0, "20190127");
INSERT INTO daqui_books(shelfno, floorno, name, author, label, borrowed, on_reading, cleaned, encoding_time) VALUES(2, 32, "王的庆宴B", "王子", "小说, 歌功颂德", 0, 0, 0, "20190127");
